name: CI

on: [push, pull_request]

jobs:

  testsute:
    name: "Testsuite"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2', '8.3' ]
        minMax: [ 'composerInstallMin', 'composerInstallMax' ]
        coreVersion: [ '12.4', '13.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s ${{ matrix.minMax }} -t ${{ matrix.coreVersion }}

      #      - name: Composer validate
      #        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s composerValidate

      #      - name: Lint PHP
      #        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

      - name: Unit tests
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit

      - name: Functional tests with mariadb
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -d mariadb -s functional
